### ISSUE TITLE
Norway and Kosovo do not have ISO3 codes assigned

### ISSUE THREAD

**Issue by Nazliozum** [ropensci/rnaturalearth#72]
I recognized that in the countries dataset, Norway and Kosovo do not have ISO3 codes assigned despite being recognized in the ISO standard. I pull the data using the ne_countries() function.

**Comment by mps9506** [comment]
You might want to try the `ne_download()` function to see if the ISO codes are updated to what you expect:

```r
countries <- ne_download(scale = "medium", type = "countries", category = "cultural", returnclass = "sf")
countries[countries$ADMIN=="Norway",]
countries[countries$ADMIN=="Kosovo",]
```

If those ISO codes are not what you expected I would suggest raising the issue in with the data producer, [Natural Earth](https://www.naturalearthdata.com/), since this package only facilities accessing and downloading the data.

**Comment by PMassicotte** [comment]
This should be working with the updated version of `rnaturalearthhighres`. Thanks to @mps9506 

```r
countries <- ne_countries(scale = "large", type = "countries", country = "Norway", returnclass = "sf")
```
